baseURL = "https://E4ik.github.io/infosec-blog/"
title = "Infosec Blog"
theme = "PaperMod"
defaultContentLanguage = "en"

[params]
  homeInfoParams = { Title = "ğŸ‘‹ æ­¡è¿ä¾†åˆ° Erik çš„è³‡å®‰ç­†è¨˜", Content = "é€™è£¡æ”¶éŒ„äº†æˆ‘åœ¨ç´…éšŠã€ADã€æ¼æ´ç ”ç©¶ç­‰å„é ˜åŸŸçš„å­¸ç¿’èˆ‡å¯¦ä½œç­†è¨˜" }
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  defaultTheme = "auto"
  env = "production"
  disableGoogleAnalytics = true
  mainSections = ["posts"]

[menu]
[[menu.main]]
  name = "Archive"
  url = "archives/"
  weight = 10

[[menu.main]]
  name = "Tags"
  url = "tags/"
  weight = 20

[[menu.main]]
  name = "Search"
  url = "search/"
  weight = 30

[languages]
  [languages.en]
    languageName = "English"
    contentDir = "content"
    weight = 1

    [languages.en.params]
      languageCode = "en-us"